# API server listen address
# Defauls to: ":8080" which will listen on all avalable interfaces.
# Overwrite with environment variable: DEVICEAUTH_LISTEN

# listen: :8080

# HTTP Server middleware environment
# Available values:
#   dev - development environment
#   prod - production environment
# Defaults to: prod
# Overwrite with environment variable: DEVICEAUTH_MIDDLEWARE

# middleware: dev

# Mongodb connection string
# Defaults to: mongo-device-adm
# Overwrite with environment variable: DEVICEAUTH_MONGO

# mongo: mongo-device-auth

# Enable SSL for mongo connections
# Defaults to: false
# Overwrite with environment variable: DEVICEAUTH_MONGO_SSL

# mongo_ssl: false

# SkipVerify controls whether a mongo client verifies the
# server's certificate chain and host name.
# If InsecureSkipVerify is true, accepts any certificate
# presented by the server and any host name in that certificate.
# Defaults to: false
# Overwrite with environment variable: DEVICEAUTH_MONGO_SSL_SKIPVERIFY

# mongo_ssl_skipverify: false

# Mongodb username
# Overwrites username set in connection string.
# Defaults to: none
# Overwrite with environment variable: DEVICEAUTH_MONGO_USERNAME

# mongo_username: user

# Mongodb password
# Overwrites password set in connection string.
# Defaults to: none
# Overwrite with environment variable: DEVICEAUTH_MONGO_PASSWORD

# mongo_password: secret

# Device admission service address
# Defaults to: http://mender-device-adm:8080
# Overwrite with environment variable: DEVICEAUTH_DEVADM_ADDR

# devadm_addr: http://mender-device-auth:8080

# Inventory service address
# Defaults to: http://mender-inventory:8080
# Overwrite with environment variable: DEVICEAUTH_INVENTORY_ADDR

# inventory_addr: http://mender-inventory:8080

# Conductor service address
# Defaults to: http://mender-conductor:8080
# Overwrite with environment variable: DEVICEAUTH_DEVICE_AUTH_ORCHESTRATOR

# device_auth_orchestrator:  http://mender-conductor:8080

# Tenant administration service address (optional)
# Defaults to: none
# Overwrite with environment variable: DEVICEAUTH_TENANTADM_ADDR

# device_auth_orchestrator:  http://tenantadm

# Private key path - used for JWT signing
# Defaults to: /etc/deviceauth/rsa/private.pem

# server_priv_key_path: /etc/deviceauth/rsa/private.pem

# JWT issuer ('iss' claim)
# Defaults to: Mender

# jwt_issuer: Mender

# JWT expiration in seconds ('exp' claim)
# Defaults to: "604800" (one week)

# jwt_exp_timeout: 604800